In [2]:
import pandas as pd

In [92]:
file = 'MERGED2008_09_PP.csv'
path = 'CollegeScorecard_Raw_Data'
combd = f'{path}/{file}'

In [93]:
testdf = pd.read_csv(combd)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (1,1537,1540,1542,1606,1614,1615) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [94]:
print(testdf.shape)

(6975, 1977)

In [95]:
filtered_df = testdf[testdf.STABBR == 'MD']

In [96]:
filtered_df = filtered_df[filtered_df.PREDDEG != 0]

In [97]:
filtered_df = filtered_df[filtered_df.PREDDEG != 1]

In [98]:
print(filtered_df.shape)

(55, 1977)

In [99]:
md_df = filtered_df.filter([
    'UNITID',
    'OPEID',
    'OPEID6',
    'INSTNM',
    'CITY',
    'STABBR',
    'ZIP',
    #'ACCREDAGENCY',
    #'INSTURL',
    #'LATITUDE',
    #'LONGITUDE',
    #'D150_4_PELL',
    #'PCTFLOAN', #Percent of all undergraduate students receiving a federal student loan
    #'UG25ABV', #Percentage of undergraduates aged 25 and above
    'PCIP01', #Agriculture, Agriculture Operations, And Related Sciences.
    'PCIP03', #Natural Resources And Conservation.
    'PCIP09', #Communication, Journalism, And Related Programs.
    'PCIP10', #Communications Technologies/Technicians And Support Services
    'PCIP11', #Computer And Information Sciences And Support Services
    'PCIP14', #Engineering
    'PCIP15', #Engineering Technologies And Engineering-Related Fields
    'PCIP26', #Biological And Biomedical Sciences
    'PCIP27', #Mathematics And Statistics
    'PCIP29', #Military Technologies And Applied Sciences
    'PCIP40', #Physical Sciences
    'PCIP41', #Science Technologies/Technicians
    'PCIP42', #Psychology
    'PCIP47', #Mechanic And Repair Technologies/Technicians
   # Only accounting for STEM related degree programs 
], axis=1)

In [100]:
md_df.head(15)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,PCIP01,PCIP03,PCIP09,...,PCIP11,PCIP14,PCIP15,PCIP26,PCIP27,PCIP29,PCIP40,PCIP41,PCIP42,PCIP47
1713,161688,205700,2057,Allegany College of Maryland,Cumberland,MD,21502-2596,0.0000,0.0156,0.0000,...,0.0016,0.0000,0.0515,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0203
1714,161767,205800,2058,Anne Arundel Community College,Arnold,MD,21012-1895,0.0006,0.0000,0.0000,...,0.0362,0.0070,0.0584,0.0000,0.0025,0.0,0.0000,0.0000,0.0000,0.0000
1717,161837,206000,2060,Baltimore Hebrew University Inc,Baltimore,MD,21215-3932,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000
1719,161864,206100,2061,Baltimore City Community College,Baltimore,MD,21215-7893,0.0000,0.0000,0.0000,...,0.0290,0.0077,0.0328,0.0000,0.0000,0.0,0.0000,0.0116,0.0000,0.0000
1720,161873,210200,2102,University of Baltimore,Baltimore,MD,21201-5720,0.0000,0.0000,0.0387,...,0.0812,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0193,0.0000
1721,161882,2314800,23148,Baltimore International College,Baltimore,MD,21202-3230,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000
1722,162007,206200,2062,Bowie State University,Bowie,MD,20715-9465,0.0000,0.0000,0.0000,...,0.0601,0.0000,0.0000,0.0552,0.0081,0.0,0.0000,0.0000,0.1169,0.0000
1723,162061,143600,1436,Capitol Technology University,Laurel,MD,20708,0.0000,0.0000,0.0000,...,0.3276,0.2586,0.2586,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000
1724,162104,830800,8308,Cecil College,North East,MD,21901-1999,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0131,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000
1725,162122,206400,2064,College of Southern Maryland,La Plata,MD,20646-0910,0.0000,0.0000,0.0000,...,0.0773,0.0120,0.0261,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000
1726,162168,465000,4650,Chesapeake College,Wye Mills,MD,21679-0008,0.0000,0.0000,0.0000,...,0.0088,0.0000,0.0220,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000
1727,162210,206700,2067,Washington Adventist University,Takoma Park,MD,20912,0.0000,0.0000,0.0432,...,0.0378,0.0000,0.0000,0.0324,0.0054,0.0,0.0054,0.0000,0.1622,0.0000
1728,162283,206800,2068,Coppin State University,Baltimore,MD,21216-3698,0.0000,0.0000,0.0000,...,0.0137,0.0000,0.0000,0.0000,0.0068,0.0,0.0000,0.0034,0.1126,0.0000
1731,162557,207100,2071,Frederick Community College,Frederick,MD,21702-2964,0.0000,0.0000,0.0000,...,0.0103,0.0000,0.0015,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0015
1732,162584,207200,2072,Frostburg State University,Frostburg,MD,21532-1099,0.0000,0.0121,0.0350,...,0.0217,0.0000,0.0000,0.0470,0.0024,0.0,0.0181,0.0000,0.1110,0.0000

In [101]:
md_df.isnull().sum()

UNITID    0
OPEID     0
OPEID6    0
INSTNM    0
CITY      0
STABBR    0
ZIP       0
PCIP01    2
PCIP03    2
PCIP09    2
PCIP10    2
PCIP11    2
PCIP14    2
PCIP15    2
PCIP26    2
PCIP27    2
PCIP29    2
PCIP40    2
PCIP41    2
PCIP42    2
PCIP47    2
dtype: int64

In [102]:
test = md_df['PCIP42'].isnull()

In [104]:
md_df.loc[test]

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,PCIP01,PCIP03,PCIP09,...,PCIP11,PCIP14,PCIP15,PCIP26,PCIP27,PCIP29,PCIP40,PCIP41,PCIP42,PCIP47
1771,164085,2578400,25784,Maryland University of Integrative Health,Laurel,MD,20723,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4838,369817,009058A1,9058,Bethel Seminary of the East,Landover,MD,20785,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
md_df = md_df[md_df.INSTNM != 'Maryland University of Integrative Health']

In [106]:
print(md_df.shape)

(54, 21)

In [107]:
md_df.isnull().sum()

UNITID    0
OPEID     0
OPEID6    0
INSTNM    0
CITY      0
STABBR    0
ZIP       0
PCIP01    1
PCIP03    1
PCIP09    1
PCIP10    1
PCIP11    1
PCIP14    1
PCIP15    1
PCIP26    1
PCIP27    1
PCIP29    1
PCIP40    1
PCIP41    1
PCIP42    1
PCIP47    1
dtype: int64

In [ ]:
file = f'MERGED{}_{}_PP.csv'

In [127]:
def pandanize(filename):
    testdf = pd.read_csv(filename)
    filtered_df = testdf[testdf.STABBR == 'MD']
    filtered_df = filtered_df[filtered_df.PREDDEG != 0]
    filtered_df = filtered_df[filtered_df.PREDDEG != 1]
    
    md_df = filtered_df.filter([
    'UNITID',
    'OPEID',
    'OPEID6',
    'INSTNM',
    'CITY',
    'STABBR',
    'ZIP',
    'PCIP01', #Agriculture, Agriculture Operations, And Related Sciences.
    'PCIP03', #Natural Resources And Conservation.
    'PCIP09', #Communication, Journalism, And Related Programs.
    'PCIP10', #Communications Technologies/Technicians And Support Services
    'PCIP11', #Computer And Information Sciences And Support Services
    'PCIP14', #Engineering
    'PCIP15', #Engineering Technologies And Engineering-Related Fields
    'PCIP26', #Biological And Biomedical Sciences
    'PCIP27', #Mathematics And Statistics
    'PCIP29', #Military Technologies And Applied Sciences
    'PCIP40', #Physical Sciences
    'PCIP41', #Science Technologies/Technicians
    'PCIP42', #Psychology
    'PCIP47', #Mechanic And Repair Technologies/Technicians
    # Only accounting for STEM related degree programs 
    ], axis=1)
    
    return md_df

In [130]:
def getFileName():
    cntr1 = 1996
    cntr2 = 0
    yrlst = [97,98,99,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
    for i in range(22):
        fname1 = str(cntr1)
        fname2 = yrlst[cntr2]
        if len(str(fname2)) < 2:
            fname2 = str('0' + str(fname2))
        
        filename = f'MERGED{fname1}_{fname2}_PP.csv'
        path = 'CollegeScorecard_Raw_Data'
        combd = f'{path}/{filename}'
        
        print(combd)
        
        pandanize(combd)
        
        cntr1 += 1
        cntr2 += 1

In [131]:
collectAll()

CollegeScorecard_Raw_Data/MERGED1996_97_PP.csv
CollegeScorecard_Raw_Data/MERGED1997_98_PP.csv
CollegeScorecard_Raw_Data/MERGED1998_99_PP.csv
CollegeScorecard_Raw_Data/MERGED1999_00_PP.csv
CollegeScorecard_Raw_Data/MERGED2000_01_PP.csv
CollegeScorecard_Raw_Data/MERGED2001_02_PP.csv
CollegeScorecard_Raw_Data/MERGED2002_03_PP.csv
CollegeScorecard_Raw_Data/MERGED2003_04_PP.csv
CollegeScorecard_Raw_Data/MERGED2004_05_PP.csv
CollegeScorecard_Raw_Data/MERGED2005_06_PP.csv
CollegeScorecard_Raw_Data/MERGED2006_07_PP.csv
CollegeScorecard_Raw_Data/MERGED2007_08_PP.csv
CollegeScorecard_Raw_Data/MERGED2008_09_PP.csv
CollegeScorecard_Raw_Data/MERGED2009_10_PP.csv
CollegeScorecard_Raw_Data/MERGED2010_11_PP.csv
CollegeScorecard_Raw_Data/MERGED2011_12_PP.csv
CollegeScorecard_Raw_Data/MERGED2012_13_PP.csv
CollegeScorecard_Raw_Data/MERGED2013_14_PP.csv
CollegeScorecard_Raw_Data/MERGED2014_15_PP.csv
CollegeScorecard_Raw_Data/MERGED2015_16_PP.csv
CollegeScorecard_Raw_Data/MERGED2016_17_PP.csv
CollegeScorecard_Raw_Data/MERGED2017_18_PP.csv

In [112]:
cntr1 = 1996
for i in range(22):
    print(f'{cntr1}')
    cntr1 += 1

1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017

In [120]:
yrlst = [97,98,99,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
for i in yrlst:
    if len(str(i)) < 2:
        i = str('0' + str(i))
    print(str(i))

97
98
99
00
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18